"""Deploy phase 6: VMware ESXi targets. The esxi integration kind and the
VMs Sirdar builds on a standalone ESXi host (the ownership record).

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-05
"""
from alembic import op

revision = "0008"
down_revision = "0007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        ALTER TABLE integrations
          DROP CONSTRAINT integrations_kind_check,
          ADD CONSTRAINT integrations_kind_check
            CHECK (kind IN ('cloudflare', 'npm', 'proxmox', 'esxi'));
        -- One row per ESXi environment: Sirdar manages only the VM whose
        -- instance UUID, name and sirdar.environment marker match this row.
        CREATE TABLE esxi_vms (
          environment_id uuid PRIMARY KEY REFERENCES environments(id) ON DELETE CASCADE,
          name text NOT NULL UNIQUE,
          -- Frozen from the integration when the environment is created.
          host text NOT NULL,
          datastore text NOT NULL,
          network text NOT NULL,
          resource_pool text,
          source_vm text NOT NULL,
          dns_servers text[] NOT NULL DEFAULT '{}',
          -- Set by step 0 the moment ESXi creates the VM.
          moref text,
          instance_uuid text UNIQUE,
          vm_path text,
          cores integer NOT NULL CHECK (cores BETWEEN 1 AND 64),
          memory_mb integer NOT NULL CHECK (memory_mb BETWEEN 2048 AND 262144),
          disk_gb integer NOT NULL CHECK (disk_gb BETWEEN 20 AND 4096),
          ip_mode text NOT NULL CHECK (ip_mode IN ('static', 'dhcp')),
          ip_cidr text,
          gateway text,
          ip text,
          ssh_public_key text NOT NULL,
          ssh_private_key_enc bytea NOT NULL,
          -- The VM's SSH host key, generated by Sirdar: the private half only
          -- until step 0 has delivered it and scrubbed the user-data.
          host_key_public text NOT NULL,
          host_key_private_enc bytea,
          keep_snapshots integer NOT NULL DEFAULT 3 CHECK (keep_snapshots BETWEEN 1 AND 10),
          created boolean NOT NULL DEFAULT false,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          CHECK ((ip_mode = 'static') = (ip_cidr IS NOT NULL AND gateway IS NOT NULL)),
          CHECK ((moref IS NULL) = (instance_uuid IS NULL)),
          CHECK (NOT created OR instance_uuid IS NOT NULL)
        );
    """)


def downgrade() -> None:
    # Environments on target 'esxi' stay: deleting them would orphan their VMs.
    # It refuses while esxi_vms (the ownership record and each VM's keys) has rows.
    op.execute("""
        DO $$
        BEGIN
          IF EXISTS (SELECT 1 FROM esxi_vms) THEN
            RAISE EXCEPTION 'Can''t downgrade below 0008 while Sirdar manages ESXi VMs; '
              'delete those environments first.';
          END IF;
        END
        $$;
        DELETE FROM integrations WHERE kind = 'esxi';
        DROP TABLE esxi_vms;
        ALTER TABLE integrations
          DROP CONSTRAINT integrations_kind_check,
          ADD CONSTRAINT integrations_kind_check
            CHECK (kind IN ('cloudflare', 'npm', 'proxmox'));
    """)
