/** The From-To import report: a two-sheet .xlsx ("Rows" and "Summary")
 *  built in the browser from a finished move-assets job's results. The
 *  builder is pure; `downloadImportReport` writes the file and hands it to
 *  the browser. Only the move's From-To import page offers it — the move
 *  wizard shares ImportReport but never renders the button. */

import * as XLSX from 'xlsx';

import type { ImportJobOut, ImportRowDetail } from './api';
import { countDetails } from './moveAssetImport';

export interface ImportReportInput {
  job: ImportJobOut;
  moveName: string;
  generatedBy: string;
  /** When the report was generated. Defaults to now; tests pass a fixed date. */
  now?: Date;
}

export interface ImportReportFile {
  filename: string;
  workbook: XLSX.WorkBook;
}

type Cell = string | number;

export const REPORT_HEADERS: Cell[] = [
  'Row', 'Serial', 'Result', 'Message', 'Make / model', 'Matched by',
  'New asset', 'Serial generated',
];

export const RESULT_LABELS: Record<ImportRowDetail['status'], string> = {
  created: 'Created', updated: 'Updated', review: 'Needs review', error: 'Error',
};

const MAX_COLUMN_WIDTH = 60;
const SLUG_MAX = 40;
const XLSX_MIME = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';

const pad2 = (n: number) => String(n).padStart(2, '0');

/** YYYY-MM-DD in the browser's local time zone (not UTC). */
export function localDay(d: Date): string {
  return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`;
}

/** YYYY-MM-DD HH:MM (24-hour) in the browser's local time zone. */
export function localDateTime(d: Date): string {
  return `${localDay(d)} ${pad2(d.getHours())}:${pad2(d.getMinutes())}`;
}

/** The move name, lower-cased, every run of characters other than ASCII
 *  letters and digits turned into one dash, dashes trimmed from both ends,
 *  capped at 40 characters (and trimmed again), or `move` when empty. */
export function moveSlug(name: string): string {
  const slug = name.toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, SLUG_MAX)
    .replace(/-+$/, '');
  return slug || 'move';
}

function yesNo(v: boolean | null | undefined): string {
  if (v === null || v === undefined) return '';
  return v ? 'Yes' : 'No';
}

/** One width per column: the longest value in it, capped at 60 characters. */
function fitColumns(rows: Cell[][]): XLSX.ColInfo[] {
  const widths: number[] = [];
  for (const row of rows) {
    row.forEach((v, i) => { widths[i] = Math.max(widths[i] ?? 0, String(v).length); });
  }
  return widths.map((w) => ({ wch: Math.min(MAX_COLUMN_WIDTH, w) }));
}

function sheetOf(rows: Cell[][]): XLSX.WorkSheet {
  const sheet = XLSX.utils.aoa_to_sheet(rows);
  sheet['!cols'] = fitColumns(rows);
  return sheet;
}

export function buildImportReport(input: ImportReportInput): ImportReportFile {
  const { job, moveName, generatedBy, now = new Date() } = input;
  const isImport = job.phase === 'commit';
  const details = [...(job.results?.details ?? [])].sort((a, b) => a.row - b.row);
  const summary = job.results?.summary ?? {};
  const fromDetails = countDetails(details);
  // The worker's summary is the source; a key it did not write falls back
  // to counting the detail rows.
  const count = (key: string, fallback: number): number => {
    const v = summary[key];
    return typeof v === 'number' ? v : fallback;
  };

  const rows: Cell[][] = [
    REPORT_HEADERS,
    ...details.map((d): Cell[] => [
      d.row,
      d.serial_number ?? '',
      RESULT_LABELS[d.status] ?? d.status,
      d.message ?? '',
      d.make_model_final ?? '',
      d.match_method ?? '',
      yesNo(d.asset_created),
      yesNo(d.serial_generated),
    ]),
  ];

  const summaryRows: Cell[][] = [
    ['Move', moveName],
    ['File', job.filename],
    ['Report', isImport ? 'Import' : 'Check (nothing imported yet)'],
    ['Generated', localDateTime(now)],
    ['Generated by', generatedBy],
    ['Created', count('created', fromDetails.created)],
    ['Updated', count('updated', fromDetails.updated)],
    ['Needs review', count('review', fromDetails.review)],
    ['Errors', count('errors', fromDetails.error)],
  ];
  if (isImport && typeof summary.collisions_flagged === 'number') {
    summaryRows.push(['Collisions flagged', summary.collisions_flagged]);
  }
  if (isImport && typeof summary.orphans_flagged === 'number') {
    summaryRows.push(['Orphan nodes flagged', summary.orphans_flagged]);
  }

  const workbook = XLSX.utils.book_new();
  // "Rows" is appended first, so it is xl/worksheets/sheet1.xml — the
  // sheet workbookBytes() gives a bold, frozen header row.
  XLSX.utils.book_append_sheet(workbook, sheetOf(rows), 'Rows');
  XLSX.utils.book_append_sheet(workbook, sheetOf(summaryRows), 'Summary');

  const kind = isImport ? 'import' : 'check';
  return {
    filename: `${moveSlug(moveName)}-from-to-${kind}-${localDay(now)}.xlsx`,
    workbook,
  };
}

// ── writing the file ─────────────────────────────────────────────────
// SheetJS Community Edition writes neither bold fonts nor frozen panes, so
// the written package is patched through its bundled zip library (CFB):
// one bold font and cell format are added to xl/styles.xml, and the Rows
// sheet's header cells use that format under a frozen first row.
//
// The patch relies on the exact XML shape SheetJS happens to write today.
// If a future SheetJS version (or a workbook shape we didn't anticipate)
// changes that XML enough that a regex no longer matches, patching fails
// or would silently produce a half-patched file. Either way we fall back
// to the unpatched but valid `raw` bytes: a plain, unstyled download beats
// a broken one.

interface ZipEntry { content: Uint8Array; size: number }
const CFB = XLSX.CFB as {
  read(data: Uint8Array, opts: { type: 'array' }): object;
  find(zip: object, path: string): ZipEntry | null;
  write(zip: object, opts: { fileType: 'zip'; type: 'array' }): ArrayLike<number>;
};

function patchEntry(zip: object, path: string, edit: (xml: string) => string): void {
  const entry = CFB.find(zip, path);
  if (!entry) throw new Error(`import report: ${path} is missing`);
  const next = new TextEncoder().encode(edit(new TextDecoder().decode(entry.content)));
  entry.content = next;
  entry.size = next.length;
}

export function workbookBytes(workbook: XLSX.WorkBook): Uint8Array {
  const raw = new Uint8Array(XLSX.write(workbook, { bookType: 'xlsx', type: 'array' }) as ArrayBuffer);

  try {
    const zip = CFB.read(raw, { type: 'array' });

    let boldXf = -1;
    patchEntry(zip, '/xl/styles.xml', (xml) => {
      let boldFont = -1;
      let fontsMatched = false;
      let xfsMatched = false;
      const next = xml
        .replace(/<fonts count="(\d+)">(<font>[\s\S]*?<\/font>)([\s\S]*?)<\/fonts>/,
          (_m, n: string, first: string, rest: string) => {
            fontsMatched = true;
            boldFont = Number(n);
            const bold = first.replace('<font>', '<font><b/>');
            return `<fonts count="${boldFont + 1}">${first}${rest}${bold}</fonts>`;
          })
        .replace(/<cellXfs count="(\d+)">([\s\S]*?)<\/cellXfs>/,
          (_m, n: string, xfs: string) => {
            xfsMatched = true;
            boldXf = Number(n);
            return `<cellXfs count="${boldXf + 1}">${xfs}`
              + `<xf numFmtId="0" fontId="${boldFont}" fillId="0" borderId="0" xfId="0" applyFont="1"/>`
              + '</cellXfs>';
          });
      if (!fontsMatched || !xfsMatched) {
        throw new Error('import report: styles.xml did not match the expected shape');
      }
      return next;
    });
    if (boldXf < 0) throw new Error('import report: styles.xml has no cellXfs');

    patchEntry(zip, '/xl/worksheets/sheet1.xml', (xml) => {
      let viewMatched = false;
      let rowMatched = false;
      const next = xml
        .replace('<sheetView workbookViewId="0"/>', () => {
          viewMatched = true;
          return '<sheetView workbookViewId="0">'
            + '<pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/>'
            + '</sheetView>';
        })
        .replace(/<row r="1"([^>]*)>([\s\S]*?)<\/row>/, (_m, attrs: string, cells: string) => {
          rowMatched = true;
          return `<row r="1"${attrs}>${cells.replace(/<c r="([A-Z]+1)"/g, `<c r="$1" s="${boldXf}"`)}</row>`;
        });
      if (!viewMatched || !rowMatched) {
        throw new Error('import report: sheet1.xml did not match the expected shape');
      }
      return next;
    });

    return new Uint8Array(CFB.write(zip, { fileType: 'zip', type: 'array' }));
  } catch {
    // Styling is cosmetic; a plain, unstyled but valid workbook is better
    // than a broken download or a silently half-patched file.
    return raw;
  }
}

/** Writes the workbook and hands it to the browser as a download. */
export function downloadImportReport(report: ImportReportFile): void {
  const blob = new Blob([workbookBytes(report.workbook)], { type: XLSX_MIME });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = report.filename;
  a.click();
  URL.revokeObjectURL(url);
}
