/** Step 7: every choice, then one Deploy (the flow owns the button). No secret is ever shown. */
import { Link } from 'react-router-dom';

import { KIND_LABEL, OPTIONAL_APPS, effectiveDomain, targetChoices, targetKind } from '../flowState';

import type { StepProps } from './EnvironmentStep';

const HIDDEN = 'Set (hidden)';

export default function ReviewStep({ state, ctx, problem, created }: StepProps & {
  busy: boolean; problem: string; created: string | null;
}) {
  const kind = targetKind(state.target);
  const target = targetChoices(state, ctx).find((t) => t.id === state.target)?.label ?? state.target;
  const apps = ['API', 'Portal', ...OPTIONAL_APPS.filter(([a]) => state.apps[a]).map(([, l]) => l)].join(', ');
  const bg = state.servers === 'bluegreen';
  const servers = bg ? (state.type === 'production' ? 'Blue/Green (blue and green)' : 'Blue/Green (orange and purple)') : 'Single server';
  const snapshot = ctx.snapshots.find((s) => s.id === state.snapshotId);
  return (
    <>
      <dl className="sirdar-kv">
        <dt>Name</dt><dd className="mono">{state.name.trim()}</dd>
        <dt>Type</dt><dd>{KIND_LABEL[state.type]}</dd>
        <dt>Servers</dt><dd>{servers}</dd>
        <dt>Target</dt><dd>{target}</dd>
        {kind === 'digitalocean' ? (
          <><dt>Sizes</dt><dd className="mono">{`${state.dropletSize} · ${state.dbSize}${state.dbStandby ? ' · standby node' : ''}`}</dd></>
        ) : (
          <><dt>Proxy IP · Bind IP</dt><dd className="mono">{`${state.proxyIp} · ${state.bindIp}`}</dd></>
        )}
        {(kind === 'esxi' || kind === 'proxmox') && (
          <><dt>Addresses</dt><dd className="mono">{bg ? `orange ${state.ipCidr} · purple ${state.purpleIpCidr} · data ${state.dataIpCidr}`
            : state.ipMode === 'dhcp' ? 'DHCP' : `${state.ipCidr} via ${state.gateway}`}</dd></>
        )}
        <dt>Git ref</dt><dd className="mono">{state.gitRef.trim()}</dd>
        <dt>Base domain</dt><dd className="mono">{effectiveDomain(state, ctx)}</dd>
        <dt>Apps</dt><dd>{apps}</dd>
        {bg && state.type !== 'production' && <><dt>Activates</dt><dd>{state.autoActivate ? 'Automatically' : 'With Activate'}</dd></>}
        {kind === 'digitalocean' && state.type !== 'production' && (
          <><dt>Certificate</dt><dd>{state.acmeStaging ? "Let's Encrypt staging" : "Let's Encrypt"}</dd></>
        )}
        <dt>DNS</dt><dd>{kind === 'digitalocean' || state.publish ? 'Published by Sirdar' : 'Set up by hand'}</dd>
        <dt>Mail</dt><dd>{state.mailMode === 'smtp' ? `SMTP ${state.smtpHost.trim()}:${state.smtpPort.trim()}` : 'Mailpit'}</dd>
        {state.mailMode === 'smtp' && state.smtpPassword && <><dt>SMTP password</dt><dd>{HIDDEN}</dd></>}
        {state.aiKey && <><dt>Anthropic API key</dt><dd>{HIDDEN}</dd></>}
        <dt>Data</dt>
        <dd>{state.dataMode === 'snapshot' ? `Snapshot ${snapshot?.name ?? ''}, restored by the first deploy` : 'Empty'}</dd>
        {state.dataMode === 'empty' && (
          <>
            <dt>First super admin</dt>
            <dd>{`${state.adminFirst.trim()} ${state.adminLast.trim()} · ${state.adminEmail.trim()}`}</dd>
            <dt>Their password</dt>
            <dd>{state.adminPasswordMode === 'invite' ? 'Generated: they get a set-password link' : HIDDEN}</dd>
          </>
        )}
        <dt>Secrets</dt><dd>Generated by Sirdar and never shown</dd>
      </dl>
      <p className="page-hint">Deploy creates the environment and starts its first deployment, then opens it.</p>
      {created && problem && (
        <p className="form-error" role="alert">
          Created {created}, but its first deployment didn't start: {problem}{' '}
          <Link to={`/deploy/environments/${encodeURIComponent(created)}`}>Open the environment</Link>
        </p>
      )}
      {created && !problem && (
        <p className="page-hint">
          Created {created}. Deploy starts its first deployment.{' '}
          <Link to={`/deploy/environments/${encodeURIComponent(created)}`}>Open the environment</Link>
        </p>
      )}
      {!created && problem && <p className="form-error" role="alert">{problem}</p>}
    </>
  );
}
